### PR TITLE
changed to validate only the name of the masters and workers

### PR DESCRIPTION
**Pull request by operst**

### CODE REVIEW

**Comment by christianh814** [comment]
@canit00 This passed testing...but can you take a look at it to see if it's okay? I know you wrote this part.

**Comment by canit00** [comment]
Definitely, glad to see improvements. Will have a quick look. TY!

**Comment by christianh814** [comment]
> 
> Finally, using `item` I introduced an invalid character into an IP address field and indeed it captured the unwanted character failing the playbook. So iterating through the all of the key:values. I think it be best to be accurate if all we care about if checking the hostnames. I will leave it up to you guise. Thank you for bringing this up to my attention.

@canit00 Did using `item.name` also catch the ipaddress bad character?

**Comment by canit00** [comment]
No, it does not. `item.name` it only checks the name portion of masters & workers.

**Comment by Bilal-io** [comment]
I am seeing the same issue. when running `ansible-playbook -e @vars-static.yaml -e staticips=true tasks/main.yml`
```bash
PLAY [all] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [fail] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: item is search('{{ chars }}')
skipping: [localhost] => (item=imbk.dev)
skipping: [localhost] => (item=helper)
skipping: [localhost] => (item=bootstrap)

TASK [fail] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: item.name is search('{{ chars }}')
skipping: [localhost] => (item={'name': 'master0', 'ipaddr': '10.11.8.21'})
skipping: [localhost] => (item={'name': 'master1', 'ipaddr': '10.11.8.22'})
skipping: [localhost] => (item={'name': 'master2', 'ipaddr': '10.11.8.23'})
skipping: [localhost] => (item={'name': 'worker0', 'ipaddr': '10.11.8.11'})
skipping: [localhost] => (item={'name': 'worker1', 'ipaddr': '10.11.8.12'})
skipping: [localhost] => (item={'name': 'worker2', 'ipaddr': '10.11.8.13'})

TASK [fail] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [file] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [openssh_keypair] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [blockinfile] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'master0', 'ipaddr': '10.11.8.21'})
ok: [localhost] => (item={'name': 'master1', 'ipaddr': '10.11.8.22'})
ok: [localhost] => (item={'name': 'master2', 'ipaddr': '10.11.8.23'})
ok: [localhost] => (item={'name': 'worker0', 'ipaddr': '10.11.8.11'})
ok: [localhost] => (item={'name': 'worker1', 'ipaddr': '10.11.8.12'})
ok: [localhost] => (item={'name': 'worker2', 'ipaddr': '10.11.8.13'})

TASK [blockinfile] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'bootstrap'})

TASK [assert] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": false,
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**Comment by christianh814** [comment]
@bilal-io what does your `vars-static.yaml` file look like?

**Comment by Bilal-io** [comment]
Thanks for the prompt response.
Here is my `vars-static.yaml`

```yaml

---
staticips: true
helper:
  name: "helper"
  ipaddr: "10.11.8.60"
dns:
  domain: "imbk.dev"
  clusterid: "ocp4"
  forwarder1: "8.8.8.8"
  forwarder2: "8.8.4.4"
bootstrap:
  name: "bootstrap"
  ipaddr: "10.11.8.20"
masters:
  - name: "master0"
    ipaddr: "10.11.8.21"
  - name: "master1"
    ipaddr: "10.11.8.22"
  - name: "master2"
    ipaddr: "10.11.8.23"
workers:
  - name: "worker0"
    ipaddr: "10.11.8.11"
  - name: "worker1"
    ipaddr: "10.11.8.12"
  - name: "worker2"
    ipaddr: "10.11.8.13"
```

I have another unrelated question, not sure if I should create a separate issue for it. 
I am using a `.dev` domain. Will the self-signed certificates work when a master node is trying to access `https://api-int.ocp4.domain.dev:22623/config/master`?

**Comment by christianh814** [comment]
> Here is my vars-static.yaml

That looks fine to me. And also the message you're getting is an expected one (it's saying it failed to find an error...I know I've been meaning to make that a better message). Are you actually getting an error in installing or were you just asking about the message?

> I have another unrelated question, not sure if I should create a separate issue for it.
> I am using a .dev domain. Will the self-signed certificates work when a master node is trying to access https://api-int.ocp4.domain.dev:22623/config/master?

OpenShift loads it's own cert into the trust bundle. It should "just work". The OpenShift doc site has information about certificates. In short, you don't need to worry about the internal certificates. Just the external ones (if you don't want them to be self signed)

https://docs.openshift.com/container-platform/4.4/authentication/certificates/api-server.html
https://docs.openshift.com/container-platform/4.4/authentication/certificates/replacing-default-ingress-certificate.html

**Comment by Bilal-io** [comment]
> And also the message you're getting is an expected one
> Are you actually getting an error in installing or were you just asking about the message?

The Ansible playbooks was not failing, the message confused me, but now it makes sense. 

> It should "just work".
That's what I like about OpenShift

Thanks a lot for your help.

**Pull request merged**
