### PR TITLE
Network Interface should be dynamic, unless set

### PR DESCRIPTION
**Pull request by canit00**
Submitting PR per `RFE: Network Interface should be dynamic, unless set`

The way that it works is if `helper.networkifacename: ""` **not** set with an iface name in your vars.yaml file, it will **dynamically** set your networkifacename using `ansible_default_ipv4.interface`

```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
  networkifacename: ""
```
Otherwise, it will configure your helper host with the iface name set in your vars.yaml file.

```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
  networkifacename: "eth0"
```
**Requirements**: double quotes `""` if **dynamically** wanting to configure your helper node.

Also improved hostname check for invalid (common) characters `!@#$%^&*()_=\/` can be improved/added to if required.

### CODE REVIEW

**Comment by christianh814** [comment]
What happens when it's null? Like this

```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
```

My idea was more of having to have less in the `vars.yaml`.

**Comment by canit00** [comment]
okay, i see what you mean. in that case it will be even easier. we can simply remove the networkifacename from the helper section as you noted  in the vars.yaml and set_facts. I'll go back and touch it up. do you want user confirmation or no?

**Comment by christianh814** [comment]
I don't think user confirmation is necessary right now.

**Comment by canit00** [comment]
Making sure the PR is on par - should the playbook take into consideration **if** the user provides a networkifacename? If not then the PR with the additional commit work.

**Comment by christianh814** [comment]
So if the user provides

```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
```

Then the playbook should use `ansible_default_ipv4.interface`


If the user provides

```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
  networkifacename: "eth0"
```

Then the playbook should use `

**Comment by christianh814** [comment]
Oops closed it by accident

**Comment by canit00** [comment]
Giving this another try.

The way that it works is if `helper.networkifacename: ""` **not** defined in your vars.yaml file, it will **dynamically** set your networkifacename using `ansible_default_ipv4.interface`

**Dynamic**
```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
```
Otherwise, the user can commit the **networkifacename** necessary.

**Explicit**
```
helper:
  name: "helper"
  ipaddr: "192.168.1.13"
  networkifacename: "eth0"
```

**Pull request merged**
