### PR TITLE
High availability feature code

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot Parab <prajyot.parab@ibm.com>

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
@christianh814 Please take a look at this and let us know in case of any issues.
cc - @bpradipt

**Comment by christianh814** [comment]
Hi @Prajyot-Parab , Thanks for getting this in! I'll review it sometime this week. I have Twitch stream to do this week, where I'm using the helpernode, so I won't merge this until sometime next week.

**Comment by christianh814** [comment]
Not a blocker...but eventually we'll have to fix this

```shell
[root@helper ~]# helpernodecheck services
Status of services:
===================
Status of dhcpd svc             ->    Active: active (running) since Tue 2020-09-01 08:23:51 PDT; 48min ago
Status of named svc             ->    Active: active (running) since Tue 2020-09-01 08:23:49 PDT; 48min ago
Status of haproxy svc           ->    Active: active (running) since Tue 2020-09-01 08:23:49 PDT; 48min ago
Status of httpd svc             ->    Active: active (running) since Tue 2020-09-01 08:23:50 PDT; 48min ago
Status of tftp svc              ->    Active: inactive (dead) since Tue 2020-09-01 08:39:31 PDT; 33min ago
Unit keepalived.service could not be found.
Status of keepalived svc                -> 
Status of local-registry svc            ->    Active: active (running) since Tue 2020-09-01 08:17:10 PDT; 55min ago
```

**Comment by Prajyot-Parab** [comment]
> Not a blocker...but eventually we'll have to fix this
> 
> ```shell
> [root@helper ~]# helpernodecheck services
> Status of services:
> ===================
> Status of dhcpd svc             ->    Active: active (running) since Tue 2020-09-01 08:23:51 PDT; 48min ago
> Status of named svc             ->    Active: active (running) since Tue 2020-09-01 08:23:49 PDT; 48min ago
> Status of haproxy svc           ->    Active: active (running) since Tue 2020-09-01 08:23:49 PDT; 48min ago
> Status of httpd svc             ->    Active: active (running) since Tue 2020-09-01 08:23:50 PDT; 48min ago
> Status of tftp svc              ->    Active: inactive (dead) since Tue 2020-09-01 08:39:31 PDT; 33min ago
> Unit keepalived.service could not be found.
> Status of keepalived svc                -> 
> Status of local-registry svc            ->    Active: active (running) since Tue 2020-09-01 08:17:10 PDT; 55min ago
> ```

@christianh814 This is while setting up without HA configs right? If that's the case then I can just move `keepalived` service out from here and have a HA specific option for the script to print all HA related services and info.

**Comment by christianh814** [comment]
@Prajyot-Parab Sorry it took so long, I'm in the middle of a move and all my testing machines have been going offline. 

This looks good for `devel` branch. Going to let it incubate there for a bit though.

**Comment by Prajyot-Parab** [comment]
@christianh814 Thanks for getting this merged into devel. Just one quick question did you get to test it with multiple bastions and setting up keepalived?

**Comment by christianh814** [comment]
@Prajyot-Parab Yes I did and I deleted the first helper and the other one picked it right up! So it worked perfectly (for this commit) for x86_64.

There might be a need to do a "quick start" as some people might confuse the 1st helper's IP with the VIP ip.

**Pull request merged**
