### PR TITLE
Add support for Power (ppc64le) architecture

### PR DESCRIPTION
**Pull request by bpradipt**
With OCP 4.3 now supporting [Power](https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html) this patch adds support for running helpernode on Power

### CODE REVIEW

**Comment by christianh814** [comment]
Nice! Will put this in the testing pipeline

**Comment by bpradipt** [comment]
thanks @christianh814

**Comment by bpradipt** [comment]
@christianh814 there is a typo in the quickstart-ppc64le.md guide where instead of using `openshift4` as the network, it's written as `default`. Please do let me know if you want me to push the change right away or wait for your review comments..

**Comment by christianh814** [comment]
> @christianh814 there is a typo in the quickstart-ppc64le.md guide where instead of using `openshift4` as the network, it's written as `default`. Please do let me know if you want me to push the change right away or wait for your review comments..

Go ahead and change it now. I will be testing this later today

**Pull request merged**
