### PR TITLE
Fixes for haproxy failover and ppc64le grub failure

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot Parab <prajyot.parab@ibm.com>

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
FYI - @christianh814

**Comment by Prajyot-Parab** [comment]
@christianh814 I am testing the newly pushed changes here, will update once validated from my end.

**Comment by Prajyot-Parab** [comment]
@christianh814 I have tested the changes and all looks good. Please take a look at this when you have some bandwidth, we were hoping to have this in master soon.

**Review by christianh814 — APPROVED** [review]
lgtm

**Pull request merged**
